version: '3.7' #version of docker-compose 

services:

  server:
    container_name: galaxies-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 5000:5000
    command: ["bash", "-c", "node api.js"]